---
version: '3.1'

volumes:
    prometheus1_data: {}
    prometheus2_data: {}
    prometheus3_data: {}
    prometheus4_data: {}
    grafana_data: {}
    minio_data: {}

services:
    prometheus-1:
        image: prom/prometheus:v2.28.1
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus1_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus1.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9081:9090
        links:
            - cadvisor:cadvisor
            - alertmanager:alertmanager
        depends_on:
            - cadvisor
        restart: always

    prometheus-2:
        image: prom/prometheus:v2.28.1
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus2_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus2.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9082:9090
        links:
            - cadvisor:cadvisor
            - alertmanager:alertmanager
        depends_on:
            - cadvisor
        restart: always

    prometheus-3:
        image: prom/prometheus:v2.28.1
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus3_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus3.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9083:9090
        links:
            - cadvisor:cadvisor
            - alertmanager:alertmanager
        depends_on:
            - cadvisor
        restart: always

    prometheus-4:
        image: prom/prometheus:v2.28.1
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus4_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus4.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9084:9090
        links:
            - cadvisor:cadvisor
            - alertmanager:alertmanager
        depends_on:
            - cadvisor
        restart: always

    thanos-sidecar-1:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus1_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-1:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-1
            - minio
        restart: always

    thanos-sidecar-2:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus2_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-2:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-2
            - minio
        restart: always

    thanos-sidecar-3:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus3_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-3:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-3
            - minio
        restart: always

    thanos-sidecar-4:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus4_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-4:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-4
            - minio
        restart: always

    thanos-query-frontend:
        image: quay.io/thanos/thanos:v0.21.1
        command:
            - 'query-frontend'
            - '--http-address=0.0.0.0:10901'
            - '--query-frontend.downstream-url=http://thanos-querier:10902'
        ports:
            - 10901:10901
        depends_on:
            - thanos-querier
        restart: always

    thanos-querier:
        image: quay.io/thanos/thanos:v0.21.1
        command:
            - 'query'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--query.replica-label=replica'
            - '--store=thanos-sidecar-1:10091'
            - '--store=thanos-sidecar-2:10091'
            - '--store=thanos-sidecar-3:10091'
            - '--store=thanos-sidecar-4:10091'
            - '--store=thanos-store-gateway:10091'
        ports:
            - 10902:10902
        depends_on:
            - thanos-sidecar-1
            - thanos-sidecar-2
            - thanos-sidecar-3
            - thanos-sidecar-4
        restart: always

    thanos-store-gateway:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'store'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--data-dir=/tmp/thanos/store'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - minio
        restart: always

    thanos-compactor:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'compact'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - '--wait'
        depends_on:
            - minio
        restart: always

    thanos-ruler:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'rule'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--eval-interval=15s'
            - '--rule-file=/etc/thanos/*.rules.yaml'
            - '--alertmanagers.url=http://alertmanager:9093'
            - '--query=thanos-querier:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - "--label=ruler_cluster=\"vegas\""
            - "--label=ruler_replica=\"r1\""
        ports:
            - 10903:10902
        depends_on:
            - minio
            - thanos-querier
        restart: always

    thanos-bucket-web:
        image: quay.io/thanos/thanos:v0.21.1
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'tools'
            - 'bucket'
            - 'web'
            - '--http-address=0.0.0.0:10902'
            - '--log.level=debug'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - '--refresh=5m'
            - '--timeout=2m'
            - '--label=replica'
        ports:
            - 10904:10902
        depends_on:
            - minio
        restart: always

    minio:
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        volumes:
            - minio_data:/data
        entrypoint: sh
        command: -c 'mkdir -p /data/demo-bucket && /usr/bin/minio server /data'
        environment:
            - MINIO_ACCESS_KEY=smth
            - MINIO_SECRET_KEY=Need8Chars
            - MINIO_PROMETHEUS_AUTH_TYPE=public
        ports:
            - 9000:9000

    node-exporter:
        image: prom/node-exporter:v1.2.0
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
        ports:
            - 9100:9100
        restart: always

    alertmanager:
        image: prom/alertmanager:v0.22.2
        ports:
            - 9093:9093
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
            - '--config.file=/etc/alertmanager/config.yaml'
            - '--storage.path=/alertmanager'

    cadvisor:
        image: gcr.io/google_containers/cadvisor:v0.36.0
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8080:8080
        restart: always

    grafana:
        image: grafana/grafana:8.0.6
        user: "104"
        depends_on:
            - prometheus-1
            - prometheus-2
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./grafana/config.monitoring
        restart: always
