# my global config
global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s  # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: 'seattle'
    replica: 'r1'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>`
  # to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and
    # scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['prometheus-3:9090', 'prometheus-4:9090']

  - job_name: 'thanos'

    # Override the global default and
    # scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets:
          - 'thanos-sidecar-3:10902'
          - 'thanos-sidecar-4:10902'
          - 'thanos-querier:10902'
          - 'thanos-store-gateway:10902'
          - 'thanos-compactor:10902'
          - 'thanos-ruler:10902'

  - job_name: 'minio'

    # Override the global default
    # and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['minio:9000']

    metrics_path: /minio/prometheus/metrics

  - job_name: 'cadvisor'

    # Override the global default
    # and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default
    # and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['node-exporter:9100']
